google/youtube-8m

- readers.py
in reader.py: added the functionality to load multiple feature groups when using video-level features
> reader.py can use multiple feature groups now

- README.md
> Merge setting the job name with the gcloud command to reinforce that it

- README.md
Other minor fixes include provide user readable time in job name.
> Add instructions to use GPUs and other minor fixes

- inference.py
Clearing devices when importing a meta graph.
> Clearing devices when importing a meta graph.

- frame_level_models.py
- train.py
> Add LSTM model.

- README.md
- convert_batch_prediction_output_to_submission.py
- convert_prediction_from_json_to_csv.py
- export_model.py
- readers.py
- train.py
Adding support for batch prediction.
> Adding support for batch prediction.

- inference.py
Change eval_data_pattern to input_data_pattern, 
as this is the correct flag-name here.
> Fix typo in flag-comment

- inference.py
Kaggle accepted submission format:
VideoId,LabelConfidencePairs
000c,1 0.5 2 0.3 3 0.1 4 0.05 5 0.05
etc.
> fix kaggle submission format in format_lines()

- eval.py
Naive Python open does not work in gcloud
> Open necessary files using file_io

- feature_extractor/feature_extractor.py
add support for parameter apply_pca for last commit
> add support for parameter apply_pca

- eval.py
- export_model.py
- inference.py
- losses.py
- readers.py
- train.py
- Fix the "op never used" warning.
- Refactor the reader to potentially support label_weight output.
> Auto-formatting, warning fix and small refactor.

- train.py
https://github.com/tensorflow/tensorflow/issues/24496
> Fix the CUDNN invalid token issue when running on RTX series GPU.

- README.md
- cloudml-4gpu.yaml
- cloudml-gpu-distributed.yaml
It gets auto-formatted again. :( 
Basically I just removed the document for multi-gpu on Google cloud.
Challenge information will be updated once it is announced.
> Remove the multi-gpu + distributed GPU support.

- eval.py
This serves as a primary step for segment-level eval.
> Lint and small fixes.

- inference.py
Tested with both python2 and 3 environment.
> Fix python3 segment ID issue in submission file.

- inference.py
> Add submission file header.

- cloudml-gpu.yaml
Tested on Google Cloud Python 2 + TF 1.14.
> Switch Google Cloud container TF version to 1.14.

- inference.py
Tested with Google Cloud Python 2 + TF 1.14.
> Reduce default batch_size to avoid frequent OOM issue during inference.

- inference.py
Tested with 
- Python2 and 3. 
- Google Cloud Python2 + TF 1.14.
> Support reading seg whitelist csv from Google Cloud.

- frame_level_models.py
Tested with python2 and 3, Google Cloud python2+TF1.14.
> Make DBoF model's activation function configurable. 

- average_precision_calculator.py
- eval.py
- eval_util.py
- export_model.py
- frame_level_models.py
- inference.py
- losses.py
- model_utils.py
- readers.py
- segment_eval_inference.py
- train.py
Tested with python 2 and 3 (inference).
> Yapf fix (only). 

- inference.py
https://www.kaggle.com/c/youtube8m-2019/overview/evaluation
> Modify per-entity inference cap default to competition default.

- eval.py
- losses.py
- readers.py
Tested with both python 2 and 3.
> TF deprecation warning fix for DBoF models on TF 1.14.
